---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ue-configmap
  labels:
    app: ueransim
    component: ue
data:
  ue-config.yaml: |
    amf: "8000"
    ciphering:
      EA1: true
      EA2: true
      EA3: true
    configured-nssai:
    - sd: 66051
      sst: 1
    default-nssai:
    - sd: 1
      sst: 1
    imei: "356938035643803"
    imeiSv: "4370816125816151"
    integrity:
      IA1: true
      IA2: true
      IA3: true
    key: 8baf473f2f8fd09487cccbd7097c6862
    mcc: "208"
    mnc: "93"
    op: 8e27b6af0e692e750f32667a3b14605d
    opType: OPC
    sessions:
    - apn: internet
      slice:
        sd: 66051
        sst: 1
      type: IPv4
    supi: imsi-208930000000003
    
    # List of gNB IP addresses for Radio Link Simulation
    gnbSearchList:
      - gnb-service

  wrapper.sh: |
    #!/bin/bash

    mkdir /dev/net
    mknod /dev/net/tun c 10 200

    ./nr-ue -c ../config/ue-config.yaml 
    
    

  ue1.yaml: |
    amf: "8000"
    ciphering:
      EA1: true
      EA2: true
      EA3: true
    configured-nssai:
    - sd: 66051
      sst: 1
    default-nssai:
    - sd: 66051
      sst: 1
    imei: "356938035643803"
    imeiSv: "4370816125816151"
    integrity:
      IA1: true
      IA2: true
      IA3: true
    key: 8baf473f2f8fd09487cccbd7097c6862
    mcc: "208"
    mnc: "93"
    op: 8e27b6af0e692e750f32667a3b14605d
    opType: OPC
    sessions:
    - apn: internet
      slice:
        sd: 66051
        sst: 1
      type: IPv4
    supi: imsi-208930000000001
    gnbSearchList:
      - gnb-service

  ue2.yaml: |
    amf: "8000"
    ciphering:
      EA1: true
      EA2: true
      EA3: true
    configured-nssai:
    - sd: 1122867
      sst: 1
    default-nssai:
    - sd: 1122867
      sst: 1
    imei: "356938035643803"
    imeiSv: "4370816125816151"
    integrity:
      IA1: true
      IA2: true
      IA3: true
    key: 8baf473f2f8fd09487cccbd7097c6862
    mcc: "208"
    mnc: "93"
    op: 8e27b6af0e692e750f32667a3b14605d
    opType: OPC
    sessions:
    - apn: internet2
      slice:
        sd: 1122867
        sst: 1
      type: IPv4
    supi: imsi-208930000000002
    gnbSearchList:
      - gnb-service

  rogers.yaml: |
    amf: "9000"
    ciphering:
      EA1: true
      EA2: true
      EA3: true
    configured-nssai:
    - sd: 1122867
      sst: 1
    default-nssai:
    - sd: 1122867
      sst: 1
    imei: "356938035643803"
    imeiSv: "4370816125816151"
    integrity:
      IA1: true
      IA2: true
      IA3: true
    key: 482256ea4b6eaca7bbd3385944bc83d8
    mcc: "999"
    mnc: "70"
    op: ed859c6baeec31790fc03b949aa8147b
    opType: OPC
    sessions:
    - apn: internet
      slice:
        sd: 1122867
        sst: 1
      type: IPv4
    supi: imsi-999700000060590
    gnbSearchList:
      - gnb-service
